#!/bin/bash

#PBS -l walltime=00:40:00
#PBS -l nodes=1:ppn=8
#PBS -l mem=8gb
#PBS -N expand_test_16384

module load Biopython/1.73-foss-2019a
module load SCOOP/0.7.1.1-GCCcore-8.2.0

echo -- Modules --
ml
echo


cd $PBS_O_WORKDIR

echo submit directory: $PWD
echo jobid: $PBS_JOBID
echo hostname: $HOSTNAME
echo
date
echo -- Start Job --

chmod 775 ../Genome_input/genome.fa
chmod 775 ./expandSeq/sequence_expand.py
chmod -R 775 ../Output/geneAnnotate/*

# Generate list of input files
ls ../Output/geneAnnotate | grep "result" | wc -l >> ./expandSeq/Input/geneAnnotate_output_7bp_dist1000.txt
chmod 775 ./expandSeq/Input/geneAnnotate_output_7bp_dist1000.txt

# Initialize output directory
outdir="../Output/expandSeq"
mkdir -p "$outdir"

# User modifiable parameters
# input="expandSeq/Input/testinput.txt"
input="expandSeq/Input/geneAnnotate_output_7bp_dist1000.txt"
distance=1000

python3 -m scoop ./expandSeq/sequence_expand.py $input $distance

echo
echo -- End Job --
date
echo